@startuml Statements
skinparam style strictuml
skinparam monochrome false


interface ASTNode #b1e8f0 {
    getLine(): int
    getColumn(): int
}

interface Statement

class If {
    condition: Expression
    ifBody: List<Statement>
    elseBody: List<Statement>
}

class IOWrite {
    expressions : List<Expression>
}

class IORead {
    expressions : List<Expression>
}

class While {
    condition : Expression
    whileBody : List<Statement>
}

class Return {
    ' Duda, esto es un Expression???
    returnType : Type
}

ASTNode <|-- Statement

Statement <|.. IOWrite
Statement <|.. IORead
Statement <|.. If
Statement <|.. While
Statement <|.. Return

' Un If debe tener una expresión
If o--"1" Expression
IOWrite o--"1" Expression
IORead o--"1" Expression
While o--"1" Expression

' Multiples Statement pueden tener un If
If o--"0..n" Statement
IOWrite o--"0..n" Statement
IORead o--"0..n" Statement
While o--"0..n" Statement
Return o--"0..n" Statement

@enduml
