@startuml Types
skinparam style strictuml
skinparam monochrome false

interface ASTNode #b1e8f0 {
    getLine(): int
    getColumn(): int
}

interface Type

class FuncType {
    params : VarDefinition
    returnType : Type
}

' Tipos simples
class IntType
class DoubleType
class CharType

Type <|.. IntType
Type <|.. DoubleType
Type <|.. CharType
Type <|.. ArrayType
Type <|.. StructType
Type <|.. FuncType

' Tipos complejos
class ArrayType {
    size : int
    type : Type
}

class StructType {
    fields : List<StructField>
}

class StructField {
    name : String
    type : Type
}

ASTNode <|-- Type
StructField --o StructType

@enduml
